### ISSUE TITLE
Image processing request takes 3s in average

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/rest-server#100]
Originally reported by: **Ingvord (Bitbucket: [Ingvord](https://bitbucket.org/Ingvord), GitHub: [Ingvord](https://github.com/Ingvord))**

----------------------------------------

Please investigate

----------------------------------------
- Bitbucket: https://bitbucket.org/hzgwpn/mtangorest.server/issue/100

**Comment by Ingvord** [comment]
*Original comment by* **Ingvord (Bitbucket: [Ingvord](https://bitbucket.org/Ingvord), GitHub: [Ingvord](https://github.com/Ingvord))**:

----------------------------------------

```
"http-bio-8080-exec-1@3803" daemon prio=5 tid=0x61 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at org.jboss.resteasy.util.Base64.encode3to4(Base64.java:503)
	  at org.jboss.resteasy.util.Base64.access$300(Base64.java:150)
	  at org.jboss.resteasy.util.Base64$OutputStream.write(Base64.java:2143)
	  at org.jboss.resteasy.util.Base64$OutputStream.write(Base64.java:2201)
	  at javax.imageio.stream.FileCacheImageOutputStream.flushBefore(FileCacheImageOutputStream.java:255)
	  at javax.imageio.stream.ImageInputStreamImpl.flush(ImageInputStreamImpl.java:825)
	  at com.sun.imageio.plugins.jpeg.JPEGImageWriter.writeOnThread(JPEGImageWriter.java:1100)
	  at com.sun.imageio.plugins.jpeg.JPEGImageWriter.write(JPEGImageWriter.java:363)
	  at javax.imageio.ImageWriter.write(ImageWriter.java:615)
	  at javax.imageio.ImageIO.doWrite(ImageIO.java:1612)
	  at javax.imageio.ImageIO.write(ImageIO.java:1578)
	  at org.tango.rest.mtango.MtangoImpl$ImageAttributeHelper.send(MtangoImpl.java:420)
	  at org.tango.rest.mtango.MtangoImpl.getCommandOrAttribute(MtangoImpl.java:307)
	  at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source:-1)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:137)
	  at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:288)
	  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:242)
	  at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:229)
	  at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:356)
	  at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:179)
	  at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:220)
	  at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	  at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	  at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	  at org.tango.web.server.filters.SimpleCacheFilter.doFilter(SimpleCacheFilter.java:37)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	  at org.tango.web.server.filters.JsonpResponseWrapper.doFilter(JsonpResponseWrapper.java:37)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	  at org.tango.web.server.filters.JsonpAuthenticationFilter.doFilter(JsonpAuthenticationFilter.java:21)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	  at org.tango.web.server.filters.TimeWatcher.doFilter(TimeWatcher.java:28)
	  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	  at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	  at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
	  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
	  at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	  - locked <0x158f> (a org.apache.tomcat.util.net.SocketWrapper)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	  at java.lang.Thread.run(Thread.java:745)
```

**Comment by Ingvord** [comment]
*Original comment by* **Ingvord (Bitbucket: [Ingvord](https://bitbucket.org/Ingvord), GitHub: [Ingvord](https://github.com/Ingvord))**:

----------------------------------------

Removing component: web-frontend (automated comment)
