### ISSUE TITLE
TangoProxy is null

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/rest-server#141]
Originally reported by: **Ingvord (Bitbucket: [Ingvord](https://bitbucket.org/Ingvord), GitHub: [Ingvord](https://github.com/Ingvord))**

----------------------------------------

```
tango-rest_1  | ERROR 2017-05-25 16:37:47,637 [http-nio-10001-exec-8 - sys/rest/0 - o.j.l.Log4jLogger] o.jboss.resteasy.resteasy_jaxrs.i18n.doLog:42 - RESTEASY002005: Failed executing GET /rest/rc4/hosts/tango-cs/10000/devices/sys/tg_test/1/commands/DevString
tango-rest_1  | org.jboss.resteasy.spi.LoggableFailure: RESTEASY003880: Unable to find contextual data of type: org.tango.client.ez.proxy.TangoProxy
tango-rest_1  |         at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:62) ~[mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at com.sun.proxy.$Proxy25.toDeviceProxy(Unknown Source) ~[na:na]
tango-rest_1  |         at org.tango.rest.DeviceCommand.get(DeviceCommand.java:44) ~[mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
tango-rest_1  |         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
tango-rest_1  |         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
tango-rest_1  |         at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
tango-rest_1  |         at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140) ~[mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294) ~[mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248) ~[mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:138) ~[mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:107) ~[mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:133) ~[mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:107) ~[mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:133) ~[mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:101) ~[mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:398) [mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:205) [mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228) [mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) [mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) [mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) [mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) [mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:632) [mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1102) [mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:788) [mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1485) [mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
tango-rest_1  |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
tango-rest_1  |         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [mtangorest.server-rc4-1.5.jar:1.5]
tango-rest_1  |         at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

```

----------------------------------------
- Bitbucket: https://bitbucket.org/hzgwpn/mtangorest.server/issue/141

**Comment by Ingvord** [comment]
*Original comment by* **Ingvord (Bitbucket: [Ingvord](https://bitbucket.org/Ingvord), GitHub: [Ingvord](https://github.com/Ingvord))**:

----------------------------------------

close issue #141
