### ISSUE TITLE
Server returns plain string in this case:

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/rest-server#158]
```
ERROR 2018-04-24 13:47:35,050 [http-nio-10001-exec-6 - development/rest/0 - o.j.r.c.ExceptionHandler] o.jboss.resteasy.resteasy_jaxrs.i18n.handleFailure:153 - RESTEASY002005: Failed executing PUT /rest/rc4/hosts/localhost/10000/devices/sys/tg_test/1/pipes/string_long_short_ro
org.jboss.resteasy.spi.ReaderException: java.lang.NullPointerException
	at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:180) ~[resteasy-jaxrs-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.resteasy.core.MethodInjectorImpl.injectArguments(MethodInjectorImpl.java:92) ~[resteasy-jaxrs-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:115) ~[resteasy-jaxrs-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294) ~[resteasy-jaxrs-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248) ~[resteasy-jaxrs-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:138) ~[resteasy-jaxrs-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:107) ~[resteasy-jaxrs-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:133) ~[resteasy-jaxrs-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:107) ~[resteasy-jaxrs-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:133) ~[resteasy-jaxrs-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:101) ~[resteasy-jaxrs-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:398) ~[resteasy-jaxrs-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:205) ~[resteasy-jaxrs-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228) ~[resteasy-jaxrs-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56) ~[resteasy-jaxrs-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51) ~[resteasy-jaxrs-3.1.2.Final.jar:3.1.2.Final]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [tomcat-embed-core-8.5.2.jar:8.5.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) [tomcat-embed-core-8.5.2.jar:8.5.2]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.2.jar:8.5.2]
	at org.tango.web.server.filters.AuthorizationCorsFilter.doFilter(AuthorizationCorsFilter.java:17) [classes/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) [tomcat-embed-core-8.5.2.jar:8.5.2]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) [tomcat-embed-core-8.5.2.jar:8.5.2]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) [tomcat-embed-core-8.5.2.jar:8.5.2]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) [tomcat-embed-core-8.5.2.jar:8.5.2]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:632) [tomcat-embed-core-8.5.2.jar:8.5.2]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.2.jar:8.5.2]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.5.2.jar:8.5.2]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620) [tomcat-embed-core-8.5.2.jar:8.5.2]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.2.jar:8.5.2]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [tomcat-embed-core-8.5.2.jar:8.5.2]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1102) [tomcat-embed-core-8.5.2.jar:8.5.2]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.2.jar:8.5.2]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:788) [tomcat-embed-core-8.5.2.jar:8.5.2]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1485) [tomcat-embed-core-8.5.2.jar:8.5.2]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.2.jar:8.5.2]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: java.lang.NullPointerException: null
	at org.tango.web.server.resolvers.JacksonConfiguration$PipeBlobDeserializer.deserialize(JacksonConfiguration.java:454) ~[classes/:na]
	at org.tango.web.server.resolvers.JacksonConfiguration$PipeBlobDeserializer.deserialize(JacksonConfiguration.java:449) ~[classes/:na]
	at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2704) ~[jackson-mapper-asl-1.9.13.jar:1.9.13]
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1315) ~[jackson-mapper-asl-1.9.13.jar:1.9.13]
	at org.codehaus.jackson.jaxrs.JacksonJsonProvider.readFrom(JacksonJsonProvider.java:419) ~[jackson-jaxrs-1.9.13.jar:1.9.13]
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.readFrom(AbstractReaderInterceptorContext.java:66) ~[resteasy-jaxrs-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.resteasy.core.interception.jaxrs.ServerReaderInterceptorContext.readFrom(ServerReaderInterceptorContext.java:61) ~[resteasy-jaxrs-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.resteasy.core.interception.jaxrs.AbstractReaderInterceptorContext.proceed(AbstractReaderInterceptorContext.java:56) ~[resteasy-jaxrs-3.1.2.Final.jar:3.1.2.Final]
	at org.jboss.resteasy.core.MessageBodyParameterInjector.inject(MessageBodyParameterInjector.java:147) ~[resteasy-jaxrs-3.1.2.Final.jar:3.1.2.Final]
	... 37 common frames omitted
```

Must return proper error object

**Comment by Ingvord** [comment]
Client side code:

```javascript
TangoWebapp.UserAction.writePipe(pipe, {
                    
                });
```
