### ISSUE TITLE
Investigate Tango events stream error

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/rest-server#184]
```
Dec 01 12:04:01 hzgxenvtest tomcat9[7733]: Server returns  tcp://172.17.0.1:49154
Dec 01 12:04:01 hzgxenvtest tomcat9[7733]: Host address is 131.169.65.123
Dec 01 12:04:01 hzgxenvtest tomcat9[7733]: tcp://172.17.0.1:49155 Failed:   Connection refused (Connection refused)
Dec 01 12:04:01 hzgxenvtest tomcat9[7733]: tcp://172.17.0.1:49154 Failed:   Connection refused (Connection refused)
Dec 01 12:03:51 hzgxenvtest tomcat9[7733]: tcp://172.17.0.1:49156 Failed:   Connection refused (Connection refused)
Dec 01 12:03:51 hzgxenvtest tomcat9[7733]: tcp://172.17.0.1:49156 Failed:   Connection refused (Connection refused)
Dec 01 12:03:41 hzgxenvtest tomcat9[7733]: tcp://172.17.0.1:49156 Failed:   Connection refused (Connection refused)
Dec 01 12:03:41 hzgxenvtest tomcat9[7733]: tcp://172.17.0.1:49156 Failed:   Connection refused (Connection refused)
Dec 01 12:03:31 hzgxenvtest tomcat9[7733]: tcp://172.17.0.1:49156 Failed:   Connection refused (Connection refused)
Dec 01 12:03:31 hzgxenvtest tomcat9[7733]: tcp://172.17.0.1:49156 Failed:   Connection refused (Connection refused)
Dec 01 12:03:21 hzgxenvtest tomcat9[7733]: tcp://172.17.0.1:49156 Failed:   Connection refused (Connection refused)
Dec 01 12:03:21 hzgxenvtest tomcat9[7733]: tcp://172.17.0.1:49156 Failed:   Connection refused (Connection refused)
Dec 01 12:03:17 hzgxenvtest tomcat9[7733]: tcp://172.17.0.1:49156 Failed:   Connection refused (Connection refused)
Dec 01 12:03:17 hzgxenvtest tomcat9[7733]: tcp://172.17.0.1:49156 Failed:   Connection refused (Connection refused)
Dec 01 12:03:01 hzgxenvtest tomcat9[7733]: tcp://172.17.0.1:49156 Failed:   Connection refused (Connection refused)
Dec 01 12:03:01 hzgxenvtest tomcat9[7733]: tcp://172.17.0.1:49156 Failed:   Connection refused (Connection refused)
Dec 01 12:02:51 hzgxenvtest tomcat9[7733]: tcp://172.17.0.1:49156 Failed:   Connection refused (Connection refused)
Dec 01 12:02:51 hzgxenvtest tomcat9[7733]: tcp://172.17.0.1:49156 Failed:   Connection refused (Connection refused)
Dec 01 12:02:41 hzgxenvtest tomcat9[7733]: tcp://172.17.0.1:49156 Failed:   Connection refused (Connection refused)
Dec 01 12:02:41 hzgxenvtest tomcat9[7733]: tcp://172.17.0.1:49156 Failed:   Connection refused (Connection refused)
Dec 01 12:02:41 hzgxenvtest tomcat9[7733]:     at java.lang.Thread.run(Thread.java:748)
Dec 01 12:02:41 hzgxenvtest tomcat9[7733]:     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
Dec 01 12:02:41 hzgxenvtest tomcat9[7733]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Dec 01 12:02:41 hzgxenvtest tomcat9[7733]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Dec 01 12:02:41 hzgxenvtest tomcat9[7733]:     at org.apache.coyote.http2.StreamRunnable.run(StreamRunnable.java:35)
Dec 01 12:02:41 hzgxenvtest tomcat9[7733]:     at org.apache.coyote.http2.StreamProcessor.process(StreamProcessor.java:76)
Dec 01 12:02:41 hzgxenvtest tomcat9[7733]: org.apache.coyote.http2.ConnectionException: Connection [92], Stream [1,139], An error occurred during processing that was fatal to the connection
Dec 01 12:02:41 hzgxenvtest tomcat9[7733]: Connection [92], Stream [1,139], An error occurred during processing that was fatal to the connection
Dec 01 12:02:41 hzgxenvtest tomcat9[7733]:     at java.lang.Thread.run(Thread.java:748)
Dec 01 12:02:41 hzgxenvtest tomcat9[7733]:     at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
Dec 01 12:02:41 hzgxenvtest tomcat9[7733]:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Dec 01 12:02:41 hzgxenvtest tomcat9[7733]:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Dec 01 12:02:41 hzgxenvtest tomcat9[7733]:     at org.apache.coyote.http2.StreamRunnable.run(StreamRunnable.java:35)
Dec 01 12:02:41 hzgxenvtest tomcat9[7733]:     at org.apache.coyote.http2.StreamProcessor.process(StreamProcessor.java:76)
Dec 01 12:02:41 hzgxenvtest tomcat9[7733]: org.apache.coyote.http2.ConnectionException: Connection [92], Stream [177], An error occurred during processing that was fatal to the connection
Dec 01 12:02:41 hzgxenvtest tomcat9[7733]: Connection [92], Stream [177], An error occurred during processing that was fatal to the connection
```

**Comment by Ingvord** [comment]
The error occurs on a machine with docker containers running due to `ZmqEventConsumer#checkWithHostAddress`:

```
if (! lsa.svalue[0].startsWith("tcp://"+hostAddress)) { //  Addresses are different
                 String  wrongAdd = lsa.svalue[0];
                 int idx = lsa.svalue[0].lastIndexOf(':');   //  get port
                 if (idx>0) {
                     lsa.svalue[0] = "tcp://" + hostAddress + lsa.svalue[0].substring(idx);
                     lsa.svalue[1] = "tcp://" + hostAddress + lsa.svalue[1].substring(idx);  // <----- accessing array by `1` while `idx` was calculated from `0`!!!!
                 }
            }
```

![Screenshot_20191201_190644](https://user-images.githubusercontent.com/11678364/69918066-c954f380-146d-11ea-9a12-b4fee1676d97.png)


Has to be fixed in JTango

**Comment by Ingvord** [comment]
Fixed in upstream
