### ISSUE TITLE
command execution with non-trivial argin fails in 1.18

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/rest-server#188]
```
PUT http://localhost:10001/tango/rest/v11/hosts/localhost/devices/sys/tg_test/1/commands/DevVarDoubleArray

{"host":"localhost:10000","device":"sys/tg_test/1","name":"DevVarDoubleArray","input":[3.14,2.87,19.84]}
```

Results in  

```
ERROR 2020-04-23 20:59:52,443 [http-nio-10001-exec-4 - test/rest/0 - f.s.t.c.u.TypeConversionUtil] f.s.t.c.util.TypeConversionUtil.castToType:116 - convertion error
net.entropysoft.transmorph.ConverterException: Could not convert given object with class '[Ljava.util.ArrayList;' to object with type signature 'class [D'
	at net.entropysoft.transmorph.converters.MultiConverter.doConvert(MultiConverter.java:145)
	at net.entropysoft.transmorph.converters.AbstractConverter.convert(AbstractConverter.java:51)
	at net.entropysoft.transmorph.Transmorph.convert(Transmorph.java:148)
	at net.entropysoft.transmorph.Transmorph.convert(Transmorph.java:124)
	at net.entropysoft.transmorph.Transmorph.convert(Transmorph.java:106)
	at fr.soleil.tango.clientapi.util.TypeConversionUtil.castToType(TypeConversionUtil.java:114)
	at fr.soleil.tango.clientapi.command.CommandInserters$DoubleInserterArray.insert(CommandInserters.java:179)
	at fr.soleil.tango.clientapi.InsertExtractUtils.insert(InsertExtractUtils.java:221)
	at fr.soleil.tango.clientapi.command.RealCommand.insert(RealCommand.java:314)
	at fr.soleil.tango.clientapi.command.RealCommand.executeExtract(RealCommand.java:129)
	at fr.soleil.tango.clientapi.TangoCommand.executeExtract(TangoCommand.java:143)
	at org.tango.web.server.proxy.TangoCommandProxyImpl.executeExtract(TangoCommandProxyImpl.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:79)
	at com.sun.proxy.$Proxy55.executeExtract(Unknown Source)
	at org.tango.rest.v10.JaxRsTangoCommand.put(JaxRsTangoCommand.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:510)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:400)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:364)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:355)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:366)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:338)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:137)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:106)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:132)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:106)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:132)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:106)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:132)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:100)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:439)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:355)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:666)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: net.entropysoft.transmorph.ConverterException: Could not convert given object with class '[Ljava.util.ArrayList;' to object with type signature 'class [D'
	at net.entropysoft.transmorph.converters.MultiConverter.doConvert(MultiConverter.java:145)
	at net.entropysoft.transmorph.converters.AbstractConverter.convert(AbstractConverter.java:51)
	at net.entropysoft.transmorph.converters.MultiConverter.doConvert(MultiConverter.java:132)
	... 66 common frames omitted
Caused by: net.entropysoft.transmorph.ConverterException: Could not convert given object with class '[Ljava.util.ArrayList;' to object with type signature 'class [D'
	at net.entropysoft.transmorph.converters.MultiConverter.doConvert(MultiConverter.java:153)
	at net.entropysoft.transmorph.converters.AbstractConverter.convert(AbstractConverter.java:51)
	at net.entropysoft.transmorph.converters.MultiConverter.doConvert(MultiConverter.java:114)
	... 68 common frames omitted
```

```
PUT http://localhost:10001/tango/rest/v11/hosts/localhost/devices/sys/tg_test/1/commands/DevVarDoubleStringArray

{"host":"localhost:10000","device":"sys/tg_test/1","name":"DevVarDoubleStringArray","input":{"svalue":["Hello","World","!!!"],"dvalue":[3.14,2.87,19.84]}}
```

Results in 

```
ERROR 2020-04-23 20:59:52,600 [http-nio-10001-exec-5 - test/rest/0 - o.t.u.DevFailedUtils] org.tango.utils.DevFailedUtils.newDevFailed:22 - TANGO_WRONG_DATA_ERROR, command type not supported 18
ERROR 2020-04-23 20:59:52,602 [http-nio-10001-exec-5 - test/rest/0 - o.t.u.DevFailedUtils] org.tango.utils.DevFailedUtils.newDevFailed:24 - 
fr.esrf.Tango.DevFailed: TANGO_WRONG_DATA_ERROR
	at org.tango.utils.DevFailedUtils.newDevFailed(DevFailedUtils.java:23)
	at fr.soleil.tango.clientapi.factory.InsertExtractFactory.getCommandInserter(InsertExtractFactory.java:54)
	at fr.soleil.tango.clientapi.InsertExtractUtils.insert(InsertExtractUtils.java:221)
	at fr.soleil.tango.clientapi.command.RealCommand.insert(RealCommand.java:314)
	at fr.soleil.tango.clientapi.command.RealCommand.executeExtract(RealCommand.java:129)
	at fr.soleil.tango.clientapi.TangoCommand.executeExtract(TangoCommand.java:143)
	at org.tango.web.server.proxy.TangoCommandProxyImpl.executeExtract(TangoCommandProxyImpl.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:79)
	at com.sun.proxy.$Proxy55.executeExtract(Unknown Source)
	at org.tango.rest.v10.JaxRsTangoCommand.put(JaxRsTangoCommand.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:139)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:510)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:400)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$0(ResourceMethodInvoker.java:364)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:355)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:366)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:338)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:137)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:106)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:132)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:106)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:132)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:106)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:132)
	at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:100)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:439)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:229)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:135)
	at org.jboss.resteasy.core.interception.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:355)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:138)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:215)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:666)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1594)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

```
PUT http://localhost:10001/tango/rest/v11/hosts/localhost/devices/sys/tg_test/1/commands/DevVarStringArray

{"host":"localhost:10000","device":"sys/tg_test/1","name":"DevVarStringArray","input":["Hello","World","!!!"]}
```

Results in (Note output => Single string instead of an array)

```
{"host":"localhost:10000","device":"sys/tg_test/1","name":"DevVarStringArray","input":["Hello","World","!!!"],"output":["[Hello, World, !!!]"]}
```

**Comment by Ingvord** [comment]
There seems to be two reasons:

1. Poor implementation of TangoCommand from JTangoClientLang
2. Incorrect deserialization of the message body
