### ISSUE TITLE
Frontend fails return error when remote Tango is not imported

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/rest-server#32]
Originally reported by: **HZG/WPN (Bitbucket: [hzgwpn](https://bitbucket.org/hzgwpn), GitHub: Unknown)**

----------------------------------------

```
http-apr-8080-exec-8 TangoProxyServlet INFO message received:CommandInfo{argin=n
ull, target=State, type=execute}
http-apr-8080-exec-9 TangoProxyServlet INFO message received:CommandInfo{argin=n
ull, target=crtActivity, type=read}
http-apr-8080-exec-8 TangoProxyServlet ERROR Request processing failed!
java.lang.NullPointerException
http-apr-8080-exec-9 TangoProxyServlet ERROR Request processing failed!
hzg.wpn.mtango.command.CommandExecutionException: java.lang.reflect.InvocationTa
rgetException
        at hzg.wpn.mtango.command.CommandImpl.execute(CommandImpl.java:27)
        at hzg.wpn.mtango.TangoProxyServlet.doGet(TangoProxyServlet.java:84)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(Appl
icationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationF
ilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperV
alve.java:224)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextV
alve.java:169)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(Authentica
torBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.j
ava:168)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.j
ava:98)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:
928)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineVal
ve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.jav
a:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp
11Processor.java:987)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(
AbstractProtocol.java:539)
        at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoin
t.java:1815)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:615)
        at java.lang.Thread.run(Thread.java:722)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor130.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at hzg.wpn.mtango.command.CommandImpl.execute(CommandImpl.java:25)
        ... 19 more
Caused by: wpn.hdri.tango.proxy.TangoProxyException: java.lang.Exception: Device
 threw an exception:
Connection(production/ss/0):TangoApi_DEVICE_NOT_EXPORTED(production/ss/0 Not Exp
orted !)
Connection.build_connection(production/ss/0):TangoApi_CANNOT_IMPORT_DEVICE(Canno
t import production/ss/0)

        at wpn.hdri.tango.proxy.TangoProxyWrapper.readAttributeValueTimeQuality(
TangoProxyWrapper.java:183)
        ... 23 more
Caused by: java.lang.Exception: Device threw an exception:
Connection(production/ss/0):TangoApi_DEVICE_NOT_EXPORTED(production/ss/0 Not Exp
orted !)
Connection.build_connection(production/ss/0):TangoApi_CANNOT_IMPORT_DEVICE(Canno
t import production/ss/0)

        at wpn.hdri.tango.util.TangoUtils.convertDevFailedToException(TangoUtils
.java:72)
        at wpn.hdri.tango.proxy.TangoProxyException.<init>(TangoProxyException.j
ava:43)
        ... 24 more
```

----------------------------------------
- Bitbucket: https://bitbucket.org/hzgwpn/mtangorest.server/issue/32

**Comment by Ingvord** [comment]
*Original comment by* **Ingvord (Bitbucket: [Ingvord](https://bitbucket.org/Ingvord), GitHub: [Ingvord](https://github.com/Ingvord))**:

----------------------------------------

Done in 1.0.1 as part of #50 -- server always returns valid json response, i.e.

```
#!javascript
{
  "errors":
      ["Can not read attribute[sys/tg_test/1/double_scalar]",
       "java.lang.Exception: Device threw an exception:\nConnection(sys/tg_test/1):TangoApi_DEVICE_NOT_EXPORTED(sys/tg_test/1 Not Exported !)\nConnection.build_connection(sys/tg_test/1):TangoApi_CANNOT_IMPORT_DEVICE(Cannot import sys/tg_test/1)\n",
      "Device threw an exception:\nConnection(sys/tg_test/1):TangoApi_DEVICE_NOT_EXPORTED(sys/tg_test/1 Not Exported !)\nConnection.build_connection(sys/tg_test/1):TangoApi_CANNOT_IMPORT_DEVICE(Cannot import sys/tg_test/1)\n"],
    "quality":"INVALID","timestamp":1425384645796}
```

**Comment by Ingvord** [comment]
*Original comment by* **Ingvord (Bitbucket: [Ingvord](https://bitbucket.org/Ingvord), GitHub: [Ingvord](https://github.com/Ingvord))**:

----------------------------------------

Removing component: web-frontend (automated comment)
