### ISSUE TITLE
Cache commands and attributes of the Tango proxy

### ISSUE THREAD

**Issue by Ingvord** [tango-controls/rest-server#85]
Originally reported by: **Ingvord (Bitbucket: [Ingvord](https://bitbucket.org/Ingvord), GitHub: [Ingvord](https://github.com/Ingvord))**

----------------------------------------

currently each request to a command first asks for the attribute of the same name. This produces a lot of junk output in the target Tango server + makes unneccessar network call:

```
ERROR 09-06-2015 15:16:22,842 [RequestProcessor-3 - DevFailedUtils] API_AttrNotFound, getLatestSnapshot does not exist
ERROR 09-06-2015 15:16:22,842 [RequestProcessor-3 - DevFailedUtils]
fr.esrf.Tango.DevFailed: IDL:Tango/DevFailed:1.0
        at org.tango.utils.DevFailedUtils.throwDevFailed(DevFailedUtils.java:43)
 [JTangoCommons-9.0.0.jar:?]
        at org.tango.server.servant.AttributeGetterSetter.getAttribute(AttributeGetterSetter.java:84) [JTangoServer-9.0.0.jar:?]
        at org.tango.server.servant.DeviceImpl.get_attribute_config_2(DeviceImpl.java:1885) [JTangoServer-9.0.0.jar:?]
        at fr.esrf.Tango.Device_5POA._invoke(Device_5POA.java:482) [JavaTangoIDL-5.0.0.jar:?]
        at org.jacorb.poa.RequestProcessor.invokeOperation(RequestProcessor.java:350) [jacorb-3.4.jar:3.4 ${jacorb_version_info}]
        at org.jacorb.poa.RequestProcessor.process(RequestProcessor.java:672) [jacorb-3.4.jar:3.4 ${jacorb_version_info}]
        at org.jacorb.poa.RequestProcessor.run(RequestProcessor.java:830) [jacorb-3.4.jar:3.4 ${jacorb_version_info}]
```

----------------------------------------
- Bitbucket: https://bitbucket.org/hzgwpn/mtangorest.server/issue/85

**Comment by Ingvord** [comment]
*Original comment by* **Ingvord (Bitbucket: [Ingvord](https://bitbucket.org/Ingvord), GitHub: [Ingvord](https://github.com/Ingvord))**:

----------------------------------------

Removing component: web-frontend (automated comment)

**Comment by Ingvord** [comment]
Done in 1.2 for v1.0
